[linux]
server01 ansible_host=192.168.20.21 ansible_user=admin
server02 ansible_host=192.168.20.22 ansible_user=admin

[windows]
winserver01 ansible_host=192.168.20.23

[windows:vars]
ansible_connection=winrm
ansible_port=5986
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_user=admin
