---
- name: Prerequisites
  apt:
    name: "{{ docker_prerequisites }}"
    state: present

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    signed_by: https://download.docker.com/linux/debian/gpg

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  notify: restart docker

- name: Add admin to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
